# run Cypress tests using CircleCI Cypress orb
# https://github.com/cypress-io/circleci-orb

version: 2.1
orbs:
  cypress: cypress-io/cypress@1.5.1
  jira: circleci/jira@1.3.0
  
executors:
  node8-lts:
    docker:
      - image: cypress/base:8.15.1

jobs:
  lint:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run types
      - run: npm run lint
      - run: echo "Hello Jira!"
      - jira/notify
      - store_test_results:
          path: /test-reports      

workflows:
  build:
    jobs:
      - cypress/run:
          executor: node8-lts
          name: Linux test
          record: false
          start: npm start
          post-steps:
            - jira/notify:
                job_type: build          
      - lint:
          requires:
            - Linux test
